### ISSUE TITLE
read_PNAD not working for several years

### ISSUE THREAD

**Issue by rafapereirabr** [lucasmation/microdadosBrasil#146]
Hi guys.

After downloading the PNAD for several years, I have tried to read the data but keep getting this error below despite the fact that I have not change the files address. This error also occurs for the datasets of 2009, 2011, 2012 and 2015. This error does not occur for 2014. These are the years I've tried so far.

Example:
```
# Download
  download_sourceData("PNAD", 2012, unzip = T)
  # automatically saved in the folder "PNAD_reponderado_2012_20150814"

# read data
   df2012_dom <- read_PNAD("domicilios", i = 2012)

>You haven't specified neither the 'root_path' nor ther 'file' parameters to the function. in this case we will assume that data is in your working directory and the files are named exactly as  they have been downloaded from the source.

>[1] "DOM2012.txt"
>[1] "PNAD_reponderado_2012_20150814/2012/Dados"
character(0)
>Error in read_data(dataset = "PNAD", ft, i, root_path = root_path, file = file,  : 
>  Data not found. Check if you have unziped the data
```

**Comment by nicolassoarespinto** [comment]
@rafapereirabr Fixed now, thanks!

**Comment by rafapereirabr** [comment]
@nicolassoarespinto Thanks, but it's still not working for the data set of 2015 and the ones before 2013. I believe this is something to do with the name of the folders for those years that are 'reponderados'

**Comment by lucasmation** [comment]
The problem is that IBGE keeps changing the URL where the files are
located. We will fix that over the next two days

2017-07-26 15:37 GMT-03:00 Rafael H M Pereira <notifications@github.com>:

**Comment by rafapereirabr** [comment]
@lucasmation The problem is not so much downloading the data, but reading it. Thanks again for all the effort you guys put into this !

**Comment by nicolassoarespinto** [comment]
@rafapereirabr  My mistake, I had pushed the commit for my  fork only, please try again now.

**Comment by rafapereirabr** [comment]
Great. Thanks @nicolassoarespinto.

It's reading the data from almost all years, but It's not reading the 2015 data. Could you also check on that?

**Comment by nicolassoarespinto** [comment]
@rafapereirabr  There was an update in 2015 internal folder and dictionary that I was not aware of( tested with my local version). I hope it works now

**Comment by rafapereirabr** [comment]
it's working !!! Thanks  so much for your patience!
